apiVersion: apps/v1
kind: Deployment
metadata:
  name: readanalytics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readanalytics
  template:
    metadata:
      labels:
        app: readanalytics
    spec:
      containers:
        - name: readanalytics
          image: mcr.microsoft.com/azure-cognitive-services/vision/read:3.2-model-2022-04-30
          ports:
            - containerPort: 5000
          env:
            - name: Eula
              value: "accept"
            - name: Billing
              value: "https://YourEndpoint.cognitiveservices.azure.com/"
            - name: ApiKey
              value: "111e11c1b111111c11111c11c1c1f11e"
          resources:
            limits:
              memory: "4Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: readanalytics-service
spec:
  type: LoadBalancer
  selector:
    app: readanalytics
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000