apiVersion: apps/v1
kind: Deployment
metadata:
  name: textanalytics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: textanalytics
  template:
    metadata:
      labels:
        app: textanalytics
    spec:
      containers:
        - name: textanalytics
          image: mcr.microsoft.com/azure-cognitive-services/textanalytics/language
          ports:
            - containerPort: 5000
          env:
            - name: Eula
              value: "accept"
            - name: Billing
              value: "https://YourEndpoint.cognitiveservices.azure.com/"
            - name: ApiKey
              value: "111e11c1b111111c11111c11c1c1f11e"
          resources:
            limits:
              memory: "4Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: textanalytics-service
spec:
  type: LoadBalancer
  selector:
    app: textanalytics
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000